- project:
    check:
      jobs:
        - fi-tox-mypy
        - fi-tox-lint
        - fi-tox-format
        - fi-tox-python310
        - fi-tox-python311
        - fi-tox-python312
        - fi-tox-docs
        - fi-tox-bandit
        - fi-tox-diff-cover:
            vars:
              tox_envlist: "py312,diff-cover"
              job_dependencies: "python312"
